#!/bin/bash

echo "💰 Switching to LIVE MODE..."
echo ""

# Unset all STRIPE environment variables
unset STRIPE_SECRET_KEY
unset NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
unset STRIPE_WEBHOOK_SECRET
unset STRIPE_BUSINESS_CENTER_PRICE_ID
unset STRIPE_PULSEMARKET_RETAIL_PRICE_ID
unset STRIPE_PULSEMARKET_MEMBER_PRICE_ID
unset STRIPE_PULSEMARKET_PROMO_CODE
unset STRIPE_PULSEFLOW_RETAIL_PRICE_ID
unset STRIPE_PULSEFLOW_MEMBER_PRICE_ID
unset STRIPE_PULSEFLOW_PROMO_CODE
unset STRIPE_PULSEDRIVE_RETAIL_PRICE_ID
unset STRIPE_PULSEDRIVE_MEMBER_PRICE_ID
unset STRIPE_PULSEDRIVE_PROMO_CODE
unset STRIPE_PULSECOMMAND_RETAIL_PRICE_ID
unset STRIPE_PULSECOMMAND_MEMBER_PRICE_ID
unset STRIPE_PULSECOMMAND_PROMO_CODE
unset STRIPE_AUTOPILOT_SOCIAL_PRICE_ID
unset STRIPE_AUTOPILOT_PRO_PRICE_ID
unset STRIPE_AUTOPILOT_TEAM_PRICE_ID

echo "✅ Environment variables cleared"
echo "💰 Server will use LIVE keys from .env.local"
echo "🚀 Starting dev server..."
echo ""

npm run dev
