'use client';

// =============================================
// Compensation Glossary - Dual Ladder System
// Based on APEX_COMP_ENGINE_SPEC_FINAL.md
// =============================================

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { createClient } from '@/lib/supabase/client';

const glossaryTerms = [
  {
    term: 'Bonus Pool',
    definition: 'A pool funded by company revenue that funds incentive programs like trip incentives, fast start bonuses, car allowances, quarterly contests, and enhanced rank bonuses.',
    example: 'If company revenue is $100K, the bonus pool receives $1,715 to distribute across all programs.',
    category: 'Incentives',
  },
  {
    term: 'Business Center',
    definition: 'A $39/month subscription that provides 39 production credits toward rank advancement. It pays a fixed commission structure (not the waterfall system) with $10 to seller and $8 to direct sponsor.',
    example: 'Selling one Business Center gives you $10 commission and 39 credits toward rank requirements.',
    category: 'Products',
  },
  {
    term: 'Commission Pool',
    definition: 'The portion allocated to field compensation (44% of customer payment) that is split between seller commission (60%) and override pool (40%). Results in approximately 27.9% seller commission rate.',
    example: 'On a $100 sale, commission pool = $44. You get $26.40 (60% of pool), override pool gets $17.60 (40% of pool).',
    category: 'Commissions',
  },
  {
    term: 'Credits (Production Credits)',
    definition: 'Points earned from product sales that count toward rank advancement. Each product has a credit value (Price × Credit %). Credits replace the old BV (Business Volume) system.',
    example: 'PulseFlow at $149 retail = 149 × 50% = 75 credits toward your monthly production.',
    category: 'Core Concepts',
  },
  {
    term: 'Credit-Based Advancement',
    definition: 'The new system where ranks are achieved through production credits (not customer accounts). Personal credits + group credits determine your rank, not how many customers you have.',
    example: 'Gold rank needs 1,200 personal credits and 5,000 group credits per month, regardless of how many customers that represents.',
    category: 'Core Concepts',
  },
  {
    term: 'Cross-Credit (Tech to Insurance)',
    definition: 'Licensed agents earn insurance credits from technology product sales at 30-50% of tech credits (varies by product). Helps licensed agents advance on both ladders simultaneously.',
    example: 'Selling PulseFlow (75 tech credits) gives you 38 insurance credits as a licensed agent.',
    category: 'Dual Ladder',
  },
  {
    term: 'Direct Commission',
    definition: 'The commission you earn on your own sales, regardless of your rank. Everyone earns the same effective rate of 27.9% (60% of the commission pool).',
    example: 'Sell PulseCommand at $499 retail → You earn $139.37 direct commission, whether you\'re Starter or Elite.',
    category: 'Commissions',
  },
  {
    term: 'Dual Ladder System',
    definition: 'Apex\'s compensation structure with two independent advancement paths: Technology Ladder (9 ranks for all reps) and Insurance Ladder (6 ranks + 7 MGA tiers for licensed agents only).',
    example: 'You can be Gold on Tech Ladder and Associate on Insurance Ladder simultaneously, earning from both systems.',
    category: 'Core Concepts',
  },
  {
    term: 'Enroller Override Rule',
    definition: 'If you personally enrolled someone, you ALWAYS earn the L1 rate (30% of override pool) on their sales, regardless of where they are in your organization or what rank you are.',
    example: 'You enrolled Sarah. She\'s now 7 levels deep. You still earn 30% L1 rate on her sales because you enrolled her.',
    category: 'Overrides',
  },
  {
    term: 'Fast Start Bonus',
    definition: 'One-time bonuses paid to new reps based on their first 30 days of production: $250 for 150 credits, $500 for 500 credits, or $1,000 for 1,200 credits.',
    example: 'Generate 1,200 personal credits in your first 30 days → Earn $1,000 fast start bonus.',
    category: 'Incentives',
  },
  {
    term: 'Generation (Insurance Ladder)',
    definition: 'A layer of MGA leaders in your insurance downline. Gen 1 = MGAs you personally sponsored. Gen 2 = MGAs they sponsored. Goes up to Gen 6 for Premier MGA.',
    example: 'You sponsor Mike (becomes MGA) = Gen 1. Mike sponsors Sarah (becomes MGA) = Gen 2 in your organization.',
    category: 'Insurance Ladder',
  },
  {
    term: 'Group Credits',
    definition: 'The total production credits generated by your entire organization (everyone in your downline) for the month. One of two requirements for rank advancement.',
    example: 'You: 1,200 credits. Your team combined: 3,800 credits. Your group credits = 5,000.',
    category: 'Core Concepts',
  },
  {
    term: 'Insurance Ladder',
    definition: 'A separate advancement system for licensed insurance agents. 6 base ranks (Pre-Associate to MGA) plus 7 MGA tiers (MGA to Premier MGA) with generational override bonuses.',
    example: 'Licensed agent advances from Associate (55% commission) to Agent (70% commission) by hitting $45K in 90-day premium.',
    category: 'Dual Ladder',
  },
  {
    term: 'Leadership Pool',
    definition: 'An exclusive program for early leaders (pre-launch through Year 1). 1,000 total shares allocated. Share owners receive a portion of 1.5% of company revenue monthly. Requires Gold+ rank for payouts.',
    example: 'You have 50 shares (5% of pool). Company does $1M revenue → Pool = $15K → You get $750 that month.',
    category: 'Leadership',
  },
  {
    term: 'Level (L1, L2, L3, L4, L5)',
    definition: 'Your position in relation to team members for override calculations. L1 = personal enrollees (or enroller rule). Higher ranks unlock more levels (up to L5 for Platinum+).',
    example: 'You → Sarah (L1) → Mike (L2) → Jenny (L3). If you\'re Gold rank, you can earn overrides on all three levels.',
    category: 'Overrides',
  },
  {
    term: 'Member Price',
    definition: 'The discounted price that distributors and members pay for products. Lower than retail price. Commission and credit calculations are based on the actual price paid (member or retail).',
    example: 'PulseFlow: Member $129, Retail $149. Member sale gives you $36.03 commission and 65 credits.',
    category: 'Products',
  },
  {
    term: 'MGA (Managing General Agent)',
    definition: 'The 6th rank on the Insurance Ladder. Unlocks access to 7 MGA tiers with generational override bonuses (15% Gen 1, 5% Gen 2, etc.). Requires $150K in 90-day premium volume.',
    example: 'Hit MGA rank → Start earning generational overrides on your insurance leaders\' production.',
    category: 'Insurance Ladder',
  },
  {
    term: 'Override Bonus',
    definition: 'Additional commissions earned on your team\'s sales based on your rank and organizational levels. Higher ranks unlock more levels (L1-L5) and higher percentages.',
    example: 'Gold rank earns 30% L1, 15% L2, 10% L3, 5% L4 on each team member\'s override pool.',
    category: 'Overrides',
  },
  {
    term: 'Override Pool',
    definition: 'The portion of revenue (40% of commission pool, or 17.6% of customer payment) that is distributed to upline as override bonuses based on rank and level.',
    example: 'On a $499 sale, override pool = $87.82. This is split among upline based on their ranks and levels.',
    category: 'Overrides',
  },
  {
    term: 'Override Qualification (50 Credits)',
    definition: 'You must generate at least 50 personal credits per month to earn override bonuses, rank bonuses, and participate in bonus pool programs. Below 50 credits = direct commissions only.',
    example: 'You generate 45 credits this month → You still earn direct commissions but NO overrides or bonuses.',
    category: 'Overrides',
  },
  {
    term: 'Personal Credits',
    definition: 'Production credits you personally generate through your own sales (not your team\'s sales). One of two requirements for rank advancement.',
    example: 'You sell 5 PulseFlow (member) = 5 × 65 credits = 325 personal credits for the month.',
    category: 'Core Concepts',
  },
  {
    term: 'Personal Enrollment',
    definition: 'Someone you directly enrolled into the company using your referral link. They are permanently tied to you as their enroller (immutable), which triggers the Enroller Override Rule.',
    example: 'You share your link with 3 friends. They join. Those 3 are your personal enrollments forever.',
    category: 'Core Concepts',
  },
  {
    term: 'Rank Advancement Bonus',
    definition: 'One-time cash bonuses paid when you first achieve a new rank on the Tech Ladder. Ranges from $250 (Bronze) to $30,000 (Elite). Total potential: $93,750. Paid once per rank per lifetime.',
    example: 'Hit Gold rank for the first time → Receive $3,000 one-time bonus. Drop to Silver and re-qualify for Gold → No second bonus.',
    category: 'Incentives',
  },
  {
    term: 'Ranked Override Schedule',
    definition: 'The percentage rates you earn on each level (L1-L5) based on your current Tech Ladder rank. Higher ranks unlock more levels and higher percentages.',
    example: 'Silver: L1=30%, L2=10%, L3=5%. Gold: L1=30%, L2=15%, L3=10%, L4=5%.',
    category: 'Overrides',
  },
  {
    term: 'Retail Price',
    definition: 'The full price non-distributors pay for products. Higher than member price. Retail sales generate more credits and commissions than member sales.',
    example: 'PulseFlow: Retail $149 → 75 credits and $41.62 commission. Member $129 → 65 credits and $36.03 commission.',
    category: 'Products',
  },
  {
    term: 'Tech Ladder (Technology Ladder)',
    definition: 'The primary advancement path for all reps. 9 ranks from Starter to Elite based on personal credits, group credits, and sponsored downline rank requirements.',
    example: 'Advance from Starter (no requirements) → Bronze (150 personal, 300 group) → Silver (500 personal, 1,500 group).',
    category: 'Dual Ladder',
  },
  {
    term: 'Vesting',
    definition: 'The gradual earning of Leadership Pool shares over time. Pre-launch leaders vest over 24 months. Launch phase vests over 18 months. Growth phase vests over 12 months. Diamond rank accelerates to 100% immediately.',
    example: 'You get 100 shares with 24-month vesting. After 12 months, 50 shares are vested. Hit Diamond → Remaining 50 shares vest immediately.',
    category: 'Leadership',
  },
  {
    term: 'Commission Structure',
    definition: 'The distribution of customer payments to field compensation. Total field compensation is 44% of customer payment, split to seller commission (60% = 27.9%) and override pool (40% = 17.6%). Bonus and Leadership pools are separately funded.',
    example: 'Customer pays $100 → $44 goes to field compensation → $27.90 to you as direct commission, $17.60 to override pool for your upline.',
    category: 'Core Concepts',
  },
];

const categories = ['All', 'Core Concepts', 'Commissions', 'Overrides', 'Products', 'Incentives', 'Dual Ladder', 'Insurance Ladder', 'Leadership'];

export default function GlossaryPage() {
  const router = useRouter();
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState('All');

  useEffect(() => {
    const checkAuth = async () => {
      const supabase = createClient();
      const {
        data: { user },
      } = await supabase.auth.getUser();

      if (!user) {
        router.push('/login');
      } else {
        setIsAuthenticated(true);
      }
      setIsLoading(false);
    };

    checkAuth();
  }, [router]);

  const filteredTerms = glossaryTerms.filter((term) => {
    const matchesSearch =
      searchQuery === '' ||
      term.term.toLowerCase().includes(searchQuery.toLowerCase()) ||
      term.definition.toLowerCase().includes(searchQuery.toLowerCase()) ||
      term.example.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesCategory = selectedCategory === 'All' || term.category === selectedCategory;

    return matchesSearch && matchesCategory;
  });

  if (isLoading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-gray-600">Loading...</div>
      </div>
    );
  }

  if (!isAuthenticated) {
    return null;
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <div className="bg-gradient-to-br from-slate-800 via-slate-700 to-slate-900 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="max-w-3xl">
            <div className="mb-6">
              <Link
                href="/dashboard/compensation"
                className="text-slate-300 hover:text-white transition-colors inline-flex items-center text-sm"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Back to Compensation Plan
              </Link>
            </div>
            <h1 className="text-4xl font-bold mb-4">Compensation Glossary</h1>
            <p className="text-xl text-slate-200 leading-relaxed">
              Clear definitions of terms used in the dual-ladder compensation system.
            </p>
          </div>
        </div>
      </div>

      {/* Filter Bar */}
      <div className="sticky top-0 z-30 bg-white border-b border-slate-200 shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          {/* Search */}
          <div className="mb-4">
            <div className="relative">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <svg className="h-5 w-5 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
              </div>
              <input
                type="text"
                placeholder="Search terms..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="block w-full pl-10 pr-3 py-2.5 border border-slate-300 rounded-lg bg-white placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-slate-500 focus:border-slate-500"
              />
              {searchQuery && (
                <button
                  onClick={() => setSearchQuery('')}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-400 hover:text-slate-600"
                >
                  <svg className="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              )}
            </div>
          </div>

          {/* Category Filters */}
          <div className="flex items-center gap-2 overflow-x-auto pb-2">
            {categories.map((category) => (
              <button
                key={category}
                onClick={() => setSelectedCategory(category)}
                className={`px-4 py-2 rounded-lg text-sm font-semibold whitespace-nowrap transition-all ${
                  selectedCategory === category
                    ? 'bg-slate-900 text-white shadow-md'
                    : 'bg-slate-100 text-slate-700 hover:bg-slate-200'
                }`}
              >
                {category}
              </button>
            ))}
          </div>

          {/* Results Counter */}
          <div className="mt-3 text-sm text-slate-600">
            Showing <span className="font-semibold text-slate-900">{filteredTerms.length}</span> of{' '}
            <span className="font-semibold text-slate-900">{glossaryTerms.length}</span> terms
            {(searchQuery || selectedCategory !== 'All') && (
              <button
                onClick={() => {
                  setSearchQuery('');
                  setSelectedCategory('All');
                }}
                className="ml-3 text-slate-700 hover:text-slate-900 font-semibold"
              >
                Clear filters
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Terms List */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        {filteredTerms.length > 0 ? (
          <div className="space-y-6">
            {filteredTerms.map((term, idx) => (
              <div key={idx} className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow">
                <div className="flex items-start justify-between mb-3">
                  <h3 className="text-2xl font-bold text-slate-900">{term.term}</h3>
                  <span className="inline-block px-3 py-1 bg-slate-100 text-slate-700 text-xs font-semibold rounded-full">
                    {term.category}
                  </span>
                </div>
                <p className="text-slate-700 leading-relaxed mb-4">{term.definition}</p>
                <div className="bg-slate-50 border-l-4 border-slate-400 rounded-r-lg p-4">
                  <div className="font-semibold text-slate-900 text-sm mb-1">Example:</div>
                  <p className="text-slate-700 text-sm leading-relaxed">{term.example}</p>
                </div>
              </div>
            ))}
          </div>
        ) : (
          // Empty State
          <div className="text-center py-16">
            <div className="inline-block p-4 bg-slate-100 rounded-full mb-4">
              <svg className="w-12 h-12 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
            <h3 className="text-lg font-semibold text-slate-900 mb-2">No terms found</h3>
            <p className="text-slate-600 mb-6">
              Try adjusting your search or filter to find what you're looking for.
            </p>
            <button
              onClick={() => {
                setSearchQuery('');
                setSelectedCategory('All');
              }}
              className="bg-slate-900 text-white px-6 py-2 rounded-lg font-semibold hover:bg-slate-800 transition-colors"
            >
              Clear all filters
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
